In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv(r"C:\Users\suraj\data science\capstone\Car_details(U).csv")
data

,vehicle_uid,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,fuel_transmission,brand,price_per_km,is_diesel
0,CAR_000001,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner,1,18,Low,NaN,0.0,Petrol_Manual,Maruti,0.86,0
1,CAR_000002,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,NaN,Individual,Manual,First Owner,2,18,Low,NaN,0.0,Petrol_Manual,Maruti,2.70,0
2,CAR_000003,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner,3,13,NaN,NaN,NaN,Diesel_Manual,Hyundai,6.00,1
3,CAR_000004,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner,4,8,Low,Medium,0.0,Petrol_Manual,Datsun,5.43,0
4,CAR_000005,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner,5,11,NaN,High,0.0,Diesel_Manual,Honda,3.19,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,CAR_004336,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,NaN,Diesel,Individual,Manual,Second Owner,4336,11,Mid,High,0.0,Diesel_Manual,Hyundai,5.12,1
4336,CAR_004337,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,NaN,Second Owner,4337,11,Mid,High,0.0,Diesel_Manual,Hyundai,5.12,1
4337,CAR_004338,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner,4338,16,Low,High,NaN,Petrol_Manual,Maruti,1.33,0
4338,CAR_004339,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,NaN,Diesel,Individual,Manual,First Owner,4339,9,High,High,0.0,Diesel_Manual,Hyundai,9.61,1
4339,CAR_004340,Renault KWID RXT,2016,NaN,40000.0,Petrol,Individual,Manual,First Owner,4340,9,Low,Medium,0.0,Petrol_Manual,Renault,5.62,0

In [11]:
display(data.isnull().sum())

vehicle_uid            0
name                   0
year                   0
selling_price          0
km_driven            434
fuel                 435
seller_type            0
transmission         434
owner                  0
car_record_id          0
car_age                0
price_category       434
km_category          434
owner_count          434
fuel_transmission      0
brand                  0
price_per_km           0
is_diesel              0
dtype: int64

In [ ]:
#Q1

In [5]:
maxi=data['selling_price'].max()
mini=data['selling_price'].min()
avg = (maxi+mini)/2
data['selling_price']=data['selling_price'].fillna(avg)

In [ ]:
#Q2

In [12]:
data['km_driven'].isnull().sum()

np.int64(434)

In [13]:
data.describe()

,year,selling_price,km_driven,car_record_id,car_age,owner_count,price_per_km,is_diesel
count,4340.000000,4.340000e+03,3906.000000,4340.000000,4340.000000,3906.0,4340.000000,4340.000000
mean,2013.090783,9.027308e+05,66231.222990,2170.500000,11.909217,0.0,88.013984,0.496083
std,4.215344,1.311959e+06,47047.819626,1252.994413,4.215344,0.0,3801.519948,0.500042
min,1992.000000,2.200000e+04,1.000000,1.000000,5.000000,0.0,0.250000,0.000000
25%,2011.000000,2.250000e+05,35000.000000,1085.750000,9.000000,0.0,2.620000,0.000000
50%,2014.000000,4.000000e+05,60000.000000,2170.500000,11.000000,0.0,6.000000,0.000000
75%,2016.000000,7.500000e+05,90000.000000,3255.250000,14.000000,0.0,15.555000,1.000000
max,2020.000000,8.900000e+06,806599.000000,4340.000000,33.000000,0.0,250000.000000,1.000000

In [14]:
data["km_driven"].median()

60000.0

In [15]:
data["km_driven"] = data["km_driven"].fillna(data["km_driven"].median())

In [18]:
data['owner_count'] = data['owner_count'].fillna(0)

In [17]:
# if outlyer then use median if not outlyer then use mean and median

In [ ]:
# Q3

In [20]:
data['km_category'].isnull().sum()

np.int64(434)

In [21]:
434/2

217.0

In [22]:
mode = data['km_category'].mode()
mode

0    Medium
Name: km_category, dtype: object

In [24]:
data['km_category']=data['km_category'].fillna(mode[0],limit= 217)

In [25]:
data['km_category']=data['km_category'].fillna("High",limit= 217)

In [ ]:
#Q4

In [29]:
mode = data['price_category'].mode()
mode

0    Low
Name: price_category, dtype: object

In [30]:
data['price_category']=data['price_category'].fillna(mode[0])

In [31]:
data['transmission']=data['transmission'].fillna("Unknown")

In [ ]:
#Q5

In [33]:
data['fuel'].unique()

array(['Petrol', nan, 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [34]:
data["fuel"].isnull().sum()

np.int64(435)

In [35]:
435/5

87.0

In [36]:
data["fuel"]=data["fuel"].fillna("Petrol",limit=87)

In [37]:
data["fuel"]=data["fuel"].fillna("Diesel",limit=87)

In [38]:
data["fuel"]=data["fuel"].fillna("CNG",limit=87)

In [39]:
data["fuel"]=data["fuel"].fillna("LPG",limit=87)

In [40]:
data["fuel"]=data["fuel"].fillna("Electric",limit=87)

In [51]:
data.to_csv("cleancardata.csv",index = False)

In [52]:
pwd

'C:\\Users\\suraj\\data science\\capstone'

In [53]:
data1=data[['vehicle_uid', 'name', 'year', 'fuel', 'seller_type', 'transmission', 'owner', 'brand', 'car_age']]

In [56]:
data1.to_csv("vehicle_info.csv",index = False)

In [57]:
data2 = data[['vehicle_uid', 'selling_price', 'km_driven', 'price_category', 
'km_category']].to_csv("vehicle_sales.csv",index = False)